/* eslint-disable */
// AUTO-GENERATED by scripts/generate-symbol-registry-snapshot.ts
// Do not edit by hand. Regenerate with: npm run registry:snapshot

import type { SymbolRegistrySnapshot } from './types'

export const SYMBOL_REGISTRY_SNAPSHOT: SymbolRegistrySnapshot = {
  "generatedAt": "2026-02-22T16:16:02.375Z",
  "primarySymbol": "MES",
  "symbols": [
    {
      "code": "6E",
      "displayName": "6E",
      "shortName": "EUR/USD",
      "description": "Euro FX Futures (EUR/USD)",
      "tickSize": 0.00005,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "6E.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "6J",
      "displayName": "6J",
      "shortName": "JPY/USD",
      "description": "Japanese Yen Futures (JPY/USD)",
      "tickSize": 0,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "6J.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "BIO",
      "displayName": "BIO",
      "shortName": "BIO",
      "description": "BIO Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "BIO.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "CL",
      "displayName": "CL",
      "shortName": "Crude Oil",
      "description": "WTI Crude Oil Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "CL.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "EMD",
      "displayName": "EMD",
      "shortName": "S&P Midcap",
      "description": "S&P MidCap 400 Futures",
      "tickSize": 0.1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "EMD.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "ES",
      "displayName": "ES",
      "shortName": "E-mini S&P",
      "description": "E-mini S&P 500 Futures",
      "tickSize": 0.25,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "ES.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "GC",
      "displayName": "GC",
      "shortName": "Gold",
      "description": "Gold Futures",
      "tickSize": 0.1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "GC.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "M2K",
      "displayName": "M2K",
      "shortName": "Micro Russell",
      "description": "Micro E-mini Russell 2000 Futures",
      "tickSize": 0.1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "M2K.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "MES",
      "displayName": "MES",
      "shortName": "Micro S&P",
      "description": "Micro E-mini S&P 500 Futures",
      "tickSize": 0.25,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "MES.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "MNQ",
      "displayName": "MNQ",
      "shortName": "Micro Nasdaq",
      "description": "Micro E-mini Nasdaq-100 Futures",
      "tickSize": 0.25,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "MNQ.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "MYM",
      "displayName": "MYM",
      "shortName": "Micro Dow",
      "description": "Micro E-mini Dow Jones Futures",
      "tickSize": 1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "MYM.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "NG",
      "displayName": "NG",
      "shortName": "Nat Gas",
      "description": "Natural Gas Futures",
      "tickSize": 0.001,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "NG.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "NIY",
      "displayName": "NIY",
      "shortName": "Nikkei USD",
      "description": "Nikkei 225 USD Futures",
      "tickSize": 5,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "NIY.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "NKD",
      "displayName": "NKD",
      "shortName": "Nikkei JPY",
      "description": "Nikkei 225 JPY Futures",
      "tickSize": 5,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "NKD.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "NQ",
      "displayName": "NQ",
      "shortName": "E-mini Nasdaq",
      "description": "E-mini Nasdaq-100 Futures",
      "tickSize": 0.25,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "NQ.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "RS1",
      "displayName": "RS1",
      "shortName": "RS1",
      "description": "RS1 Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "RS1.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "RSG",
      "displayName": "RSG",
      "shortName": "RSG",
      "description": "RSG Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "RSG.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "RSV",
      "displayName": "RSV",
      "shortName": "RSV",
      "description": "RSV Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "RSV.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "RTY",
      "displayName": "RTY",
      "shortName": "E-mini Russell",
      "description": "E-mini Russell 2000 Futures",
      "tickSize": 0.1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "RTY.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "SI",
      "displayName": "SI",
      "shortName": "Silver",
      "description": "Silver Futures",
      "tickSize": 0.005,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SI.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "SOX",
      "displayName": "SOX",
      "shortName": "Semiconductor",
      "description": "PHLX Semiconductor Index Futures",
      "tickSize": 0.1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SOX.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "SR3",
      "displayName": "SR3",
      "shortName": "SOFR 3M",
      "description": "3-Month SOFR Futures",
      "tickSize": 0.0025,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SR3.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "SXB",
      "displayName": "SXB",
      "shortName": "SX B",
      "description": "SX B Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SXB.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "SXI",
      "displayName": "SXI",
      "shortName": "SX I",
      "description": "SX I Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SXI.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "SXO",
      "displayName": "SXO",
      "shortName": "SX O",
      "description": "SX O Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SXO.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "SXR",
      "displayName": "SXR",
      "shortName": "SX R",
      "description": "SX R Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SXR.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "SXT",
      "displayName": "SXT",
      "shortName": "SX T",
      "description": "SX T Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "SXT.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAB",
      "displayName": "XAB",
      "shortName": "XA B",
      "description": "XA B Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAB.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAE",
      "displayName": "XAE",
      "shortName": "XA E",
      "description": "XA E Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAE.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAF",
      "displayName": "XAF",
      "shortName": "XA F",
      "description": "XA F Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAF.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAI",
      "displayName": "XAI",
      "shortName": "XA I",
      "description": "XA I Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAI.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAK",
      "displayName": "XAK",
      "shortName": "XA K",
      "description": "XA K Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAK.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAP",
      "displayName": "XAP",
      "shortName": "XA P",
      "description": "XA P Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAP.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAR",
      "displayName": "XAR",
      "shortName": "XA R",
      "description": "XA R Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAR.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAU",
      "displayName": "XAU",
      "shortName": "XA U",
      "description": "XA U Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAU.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAV",
      "displayName": "XAV",
      "shortName": "XA V",
      "description": "XA V Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAV.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAY",
      "displayName": "XAY",
      "shortName": "XA Y",
      "description": "XA Y Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAY.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "XAZ",
      "displayName": "XAZ",
      "shortName": "XA Z",
      "description": "XA Z Futures",
      "tickSize": 0.01,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "XAZ.c.0",
      "fredSymbol": null,
      "isActive": false
    },
    {
      "code": "YM",
      "displayName": "YM",
      "shortName": "E-mini Dow",
      "description": "E-mini Dow Jones Futures",
      "tickSize": 1,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "YM.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "ZB",
      "displayName": "ZB",
      "shortName": "30Y Bond",
      "description": "30-Year Treasury Bond Futures",
      "tickSize": 0.03125,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "ZB.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "ZF",
      "displayName": "ZF",
      "shortName": "5Y Note",
      "description": "5-Year Treasury Note Futures",
      "tickSize": 0.007813,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "ZF.c.0",
      "fredSymbol": null,
      "isActive": true
    },
    {
      "code": "ZN",
      "displayName": "ZN",
      "shortName": "10Y Note",
      "description": "10-Year Treasury Note Futures",
      "tickSize": 0.015625,
      "dataSource": "DATABENTO",
      "dataset": "GLBX.MDP3",
      "databentoSymbol": "ZN.c.0",
      "fredSymbol": null,
      "isActive": true
    }
  ],
  "roleMembers": [],
  "providerMappings": [
    {
      "symbolCode": "BIO",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "BIO.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "CL",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "CL.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "EMD",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "EMD.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "ES",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "ES.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "GC",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "GC.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "M2K",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "M2K.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "MES",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "MES.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "MNQ",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "MNQ.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "MYM",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "MYM.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "NIY",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "NIY.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "NKD",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "NKD.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "NQ",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "NQ.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "RS1",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "RS1.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "RSG",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "RSG.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "RSV",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "RSV.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "RTY",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "RTY.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SI",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SI.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SOX",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SOX.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SXB",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SXB.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SXI",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SXI.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SXO",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SXO.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SXR",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SXR.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "SXT",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "SXT.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAB",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAB.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAE",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAE.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAF",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAF.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAI",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAI.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAK",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAK.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAP",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAP.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAR",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAR.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAU",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAU.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAV",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAV.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAY",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAY.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "XAZ",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "XAZ.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "YM",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "YM.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "ZB",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "ZB.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "ZF",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "ZF.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    },
    {
      "symbolCode": "ZN",
      "source": "DATABENTO",
      "sourceTable": "databento.continuous",
      "sourceSymbol": "ZN.c.0",
      "isPrimary": true,
      "confidenceScore": 1,
      "notes": null
    }
  ]
}
