import { NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";
import type { CorrelationAlignment } from "@/lib/correlation-filter";

export const runtime = "nodejs";
export const revalidate = 300;

const MES_CORRELATION_PAUSED = process.env.PAUSE_CORRELATIONS === "1";
const MES_CORRELATION_PAUSE_REASON =
  process.env.PAUSE_CORRELATIONS_REASON || "temporarily paused";

type CorrelationCadence = "intraday" | "daily" | "unavailable";

interface CorrelationMeta {
  cadence: CorrelationCadence;
  lookbackBars: number;
  observations: number;
  availableSymbols: string[];
  missingSymbols: string[];
  reason: string | null;
}

interface CorrelationResponse {
  bullish: CorrelationAlignment;
  bearish: CorrelationAlignment;
  meta: CorrelationMeta;
  timestamp: string;
}

function clamp(n: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, n));
}

export async function GET() {
  try {
    if (MES_CORRELATION_PAUSED) {
      return NextResponse.json(
        {
          error: `MES correlation endpoint paused: ${MES_CORRELATION_PAUSE_REASON}`,
          status: "paused",
          reason: "pause-flag-enabled",
          timestamp: new Date().toISOString(),
        },
        { status: 503, headers: { "Cache-Control": "no-store" } },
      );
    }

    const jsonPath = path.join(
      process.cwd(),
      "public",
      "daily-correlations.json",
    );

    if (!fs.existsSync(jsonPath)) {
      return NextResponse.json(
        { error: "Correlations not yet generated by python script." },
        { status: 503 },
      );
    }

    const rawStr = fs.readFileSync(jsonPath, "utf8");
    const corrMap = JSON.parse(rawStr); // { "nq": 0.9, "vx": -0.7, "dx": -0.1, ... }

    const vixRaw = corrMap["vx"] || 0;
    const dxyRaw = corrMap["dx"] || 0;
    const nqRaw = corrMap["nq"] || 0;

    // Compute exact same directional logic as correlation-filter.ts
    const vixScore = -vixRaw;
    const dxyScore = -dxyRaw;
    const nqScore = nqRaw;

    const composite = clamp(
      0.4 * vixScore + 0.3 * nqScore + 0.3 * dxyScore,
      -1,
      1,
    );

    const constructAlignment = (
      direction: "BULLISH" | "BEARISH",
    ): CorrelationAlignment => {
      const isAligned = direction === "BULLISH" ? composite > 0 : composite < 0;

      const parts: string[] = [];
      if (Math.abs(vixRaw) > 0.3) {
        parts.push(
          `VIX ${vixRaw > 0 ? "positive" : "inverse"} (${vixRaw.toFixed(2)})`,
        );
      }
      if (Math.abs(nqRaw) > 0.3) {
        parts.push(
          `NQ ${nqRaw > 0 ? "confirming" : "diverging"} (${nqRaw.toFixed(2)})`,
        );
      }
      if (Math.abs(dxyRaw) > 0.3) {
        parts.push(
          `DXY ${dxyRaw > 0 ? "headwind" : "tailwind"} (${dxyRaw.toFixed(2)})`,
        );
      }
      const details =
        parts.length > 0
          ? `${isAligned ? "Aligned" : "Conflicted"}: ${parts.join(", ")}`
          : `Neutral cross-asset regime (composite ${composite.toFixed(2)})`;

      return {
        vix: vixRaw,
        dxy: dxyRaw,
        nq: nqRaw,
        cl: corrMap["cl"],
        zn: corrMap["zn"],
        gc: corrMap["gc"],
        composite: Number(composite.toFixed(3)),
        isAligned,
        details,
      };
    };

    const response: CorrelationResponse = {
      bullish: constructAlignment("BULLISH"),
      bearish: constructAlignment("BEARISH"),
      meta: {
        cadence: "daily",
        lookbackBars: 180, // Using 180 trading days python lookback
        observations: Object.keys(corrMap).length,
        availableSymbols: Object.keys(corrMap),
        missingSymbols: [],
        reason: "Served dynamically via python pipeline",
      },
      timestamp: new Date().toISOString(),
    };

    return NextResponse.json(response);
  } catch (error: unknown) {
    console.error("Correlation daily sync failed:", error);
    return NextResponse.json(
      {
        error: "Internal correlation error",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
